### ISSUE TITLE
无法拦截kotlin的点击事件

### ISSUE THREAD

**Issue by sceneren** [Peakmain/AsmActualCombat#3]
`java.lang.NoSuchMethodError: No static method trackViewOnClick(Landroid/view/View;)V in class Lcom/peakmain/sdk/SensorsDataAutoTrackHelper; or its super classes (declaration of 'com.peakmain.sdk.SensorsDataAutoTrackHelper' appears in /data/data/com.zj.android_asm/code_cache/.overlay/base.apk/classes.dex)
        at com.zj.android_asm.MainActivity.onCreate$lambda-0(Unknown Source:0)
        at com.zj.android_asm.MainActivity.$r8$lambda$ux0TVI1TuLHEZiWPLhExNtiUhWA(Unknown Source:0)
        at com.zj.android_asm.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:0)
        at android.view.View.performClick(View.java:7520)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
        at android.view.View.performClickInternal(View.java:7489)
        at android.view.View.access$3600(View.java:826)
        at android.view.View$PerformClick.run(View.java:28555)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8068)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)`

代码
`binding.tvTest.setOnClickListener {
            Log.d("MainActivity", "click")
        }`

**Comment by Peakmain** [comment]
亲，你这sdk版本不对呢，可以试下最新版本呢

**Comment by sceneren** [comment]
是最新的1.1.1

**Comment by sk-huang** [comment]
lambda的方式确实有问题，会崩溃

**Comment by Peakmain** [comment]
感谢反馈，已修复。可使用插件最新版本1.1.2
