### ISSUE TITLE
编译报错麻烦看一下，谢谢了

### ISSUE THREAD

**Issue by wenbo-ya** [Peakmain/AsmActualCombat#8]
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:70)
	at com.peakmain.analytics.plugin.visitor.PeakmainVisitor.<init>(PeakmainVisitor.groovy:26)
	at jdk.internal.reflect.GeneratedConstructorAccessor642.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.peakmain.analytics.plugin.transform.MonitorAnalyticsTransform.modifyClass(MonitorAnalyticsTransform.groovy:95)
	at jdk.internal.reflect.GeneratedMethodAccessor1503.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.peakmain.analytics.plugin.transform.MonitorAnalyticsTransform.modifyJar(MonitorAnalyticsTransform.groovy:138)
	at com.peakmain.analytics.plugin.transform.MonitorAnalyticsTransform$modifyJar$5.call(Unknown Source)
	at com.peakmain.analytics.plugin.transform.MonitorTransform.transformJar(MonitorTransform.groovy:228)
	at com.peakmain.analytics.plugin.transform.MonitorTransform$transformJar$3.callCurrent(Unknown Source)
	at com.peakmain.analytics.plugin.transform.MonitorTransform.handleJarInput(MonitorTransform.groovy:212)
	at jdk.internal.reflect.GeneratedMethodAccessor1500.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.peakmain.analytics.plugin.transform.MonitorTransform.this$dist$invoke$2(MonitorTransform.groovy)
	at com.peakmain.analytics.plugin.transform.MonitorTransform$2.methodMissing(MonitorTransform.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor1502.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.peakmain.analytics.plugin.transform.MonitorTransform$2.call(MonitorTransform.groovy:111)

**Comment by wenbo-ya** [comment]
定位到这里了
  /**
   * Constructs a new {@link ClassVisitor}.
   *
   * @param api the ASM API version implemented by this visitor. Must be one of {@link
   *     Opcodes#ASM4}, {@link Opcodes#ASM5}, {@link Opcodes#ASM6} or {@link Opcodes#ASM7}.
   * @param classVisitor the class visitor to which this visitor must delegate method calls. May be
   *     null.
   */
  public ClassVisitor(final int api, final ClassVisitor classVisitor) {
    if (api != Opcodes.ASM6 && api != Opcodes.ASM5 && api != Opcodes.ASM4 && api != Opcodes.ASM7) {
      throw new IllegalArgumentException();
    }
    this.api = api;
    this.cv = classVisitor;
  }

**Comment by Peakmain** [comment]
com.peakmain.analytics.plugin.visitor.PeakmainVisitor 类的构造函数中传递了一个非法的参数。你检查 PeakmainVisitor.groovy 文件中第 26 行的构造函数调用，你看下你传入的参数是否正确的

**Comment by wenbo-ya** [comment]
我这边项目依赖之后，org.ow2.asm:asm这个版本是7.0  我依赖个高版本的9.2就好了
